### PR TITLE
use QgsVectorLayerUtils instead of QgsFeature to support default values in FeatureForm

### PR DESCRIPTION
**Pull request by AlexanderFinkbeiner**
There was a bug fix in the Lat Lon Tool to support default values in the feature form:
https://github.com/NationalSecurityAgency/qgis-latlontools-plugin/issues/52

The same bug is also in this plugin. I provided a small fix for it.

### CODE REVIEW

**Comment by iona5** [comment]
@AlexanderFinkbeiner thanks for the heads up and your work. Will merge when i prepare the next version.

**Comment by AlexanderFinkbeiner** [comment]
Thanks! Do you know when you will release the next version?

**Comment by iona5** [comment]
i am sure the next version will be released in december. i want to make some other improvements but i do not know when i have time. if all else fails, i will create a version with your patch as only change.

**Comment by AlexanderFinkbeiner** [comment]
Okay cool thanks!

**Pull request merged**
